# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d0b3c51ecd4451c97d15b10647bf6b5afc9ea211df055feeabc98b6c87aee0f4d92417f4ed5e1f0fd70b9c348f007c433f1b529b315df71ece5da39151aaf635

test:
  secret_key_base: 436487b6ce0902275453be0f2206f108cda290bea2398bb0c93cfd4d12314869849c7e7b6190f7e971463f6528ef9145a5b629376363fb1fa3a8b1195ff4feb0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
